### ISSUE TITLE
Cython modules that use __init__.pyx instead of __init__.py are broken

### ISSUE THREAD

**Issue by JonasT** [sphinx-contrib/apidoc#13]
Cython modules that use `__init__.pyx` instead of `__init__.py` are broken and are not picked up properly. (I get a weird entry for the parent folder of the actual module and not the module itself, and that entry is not clickable so it's kind of unbrowseable)

Let me know if this is an upstream bug e.g. in `sphinx.ext.autodoc`or somewhere else, I am a little confused about sphinx's project structure :grimacing:

**Comment by stephenfin** [comment]
Yeah, this is an upstream bug and should go against [sphinx-doc/sphinx](https://github.com/sphinx-doc/sphinx). This project is simply a wrapper around the built-in functionality provided by Sphinx.
